---

## Base Vars
nexcess_repo_enabled: false
server_selinux_enforcing: false

## Allow docker to discretely map more memory; incidentally this also is needed later for ES
server_extra_sysctl:
  - key: "vm.max_map_count"
    value: 393216

## Firewall
firewall_v4_group_rules:
  401 allow all on eth1:
    - "-A INPUT -i {{ eth1 }} -s 0/0 -d 0/0 -j ACCEPT"

## Prevent puppet from running in a non-blocking fashion
puppet_agent_fire_and_forget: false
puppet_server: "yy-node62188.us-midwest-1.nexcess.net"

## this looks messy since the role always calls these with the yum module, and their defaults
##  cause yum to throw python errors. really these values can be anything, with the note that any repo
##  name used has to actually exist.
elrepo_kernel: true
elrepo_kernel_version: lt
elrepo_repository_kernel: true
elrepo_disable_plugin:
  - 'notaplugin'
elrepo_disablerepo:
  - 'remi'
elrepo_enable_plugin:
  - 'notaplugin'
elrepo_enablerepo:
  - 'epel'
