---
- name: Template daemon.json File
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: 0644
  when: mode == 'post'

- name: Restart Docker
  service:
    name: "docker"
    state: "restarted"
  when: mode == 'post'
