---

- name: "Create Override Dir For 'fix'"
  file:
    path: "/etc/systemd/system/docker.service.d/"
    owner: "root"
    group: "root"
    mode: 0755
    state: "directory"
  when: mode == 'post'

- name: "Fix Docker docker-ce-18.09.0-3.el7 Issues"
  template:
    src: "docker-override.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/override.conf"
    owner: "root"
    group: "root"
    mode: 0644
  when: mode == 'post'

- name: "Template daemon.json File"
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: 0644
  when: mode == 'post'

- name: "Restart Docker"
  service:
    name: "docker"
    state: "restarted"
    daemon_reload: true
  when: mode == 'post'

## ignore automatic reboots for now
## make sure this is always the last task
#- name: "Restart Containerhost"
#  reboot:
#    test_command: "docker info"
#  when: mode == 'post'
