---

- include: base.yml

- name: Setup a ContainerHost
  hosts: containerhost
  become: true
  any_errors_fatal: true
  pre_tasks:
    - include: tasks/containerhost.yml mode="pre"
  roles:
    - nexcess.docker
    - nexcess.secure_docker
#    - { role: nexcess.puppet, when: "nex_env_target is undefined or nex_env_target != 'vagrant'" }
#    - nexcess.repo
  post_tasks:
    - include: tasks/containerhost.yml mode="post"
